# Generated by Django 3.2.10 on 2021-12-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='site',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
