# Generated by Django 3.2.10 on 2021-12-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_auto_20211214_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='site',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='state',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='street',
            field=models.TextField(null=True),
        ),
    ]
