# Generated by Django 3.2.10 on 2021-12-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_auto_20211214_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='site',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
